game_init:
  path: ${RANKING_URL}/games/initialize/

game_read:
  path: ${RANKING_URL}/games/

match_init:
  path: ${RANKING_URL}/matches/add/

player_games_read:
  path: ${RANKING_URL}/players/games/

replay_data:
  path: ${RANKING_URL}/replay_data/